Public Class clsStoreSettings
    Public FLDStoreID As Integer
    Public FLDBranch As String
    'Public FLDAddress As String
    'Public FLDAddress2 As String
    'Public FLDBusinessName As String
    'Public FLDRegisteredName As String
    'Public FLDTIN As String
    'Public FLDMachModAcc As String
    'Public FLDBIRAccNum As String
    'Public FLDSerialNumber As String
    'Public FLDHeader1 As String
    'Public FLDHeader2 As String
    'Public FLDFooter1 As String
    'Public FLDFooter2 As String
    'Public FLDFooter3 As String
    'Public FLDVAT As Single
    'Public FLDWifiAmount As Decimal
    'Public FLDVolume As Integer
    'Public FLDServiceCharge As Single
    'Public FLDUseSAPDR As Boolean
    'Public FLDSAPServer As String
    'Public FLDSAPDB As String
    'Public FLDSAPUser As String
    'Public FLDSAPPass As String
    'Public FLDSumPathLocal As String
    'Public FLDSumPathRemote As String
    'Public FLDTenantCode As String
    'Public FLDEDFormat As String
    'Public FLDBckPath1 As String
    'Public FLDBckPath2 As String
    'Public FLDForecastPath As String
    'Public FLDSAPCardCode As String
    'Public FLDSAPPrjCode As String
    'Public FLDSAPPrjName As String
    'Public FLDSAPSeries As String
    'Public FLDSAPWhsCode As String
    'Public FLDSAPOcrCode As String
    'Public FLDSupplier As String
    'Public FLDSupplierAddress As String
    'Public FLDSupplierTIN As String
    'Public FLDAccreditation As String
    'Public FLDAccreditationDate As Date
    'Public FLDSCMServe As String
    'Public FLDSCMPort As String
    Public FLDSCMUser As String
    Public FLDSCMPassword As String
    Public FLDSCMDatabase As String
End Class
